# Generated by Django 3.2.18 on 2023-04-10 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garage_management', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.CharField(max_length=200)),
                ('is_received', models.CharField(choices=[('no', 'no'), ('yes', 'tes'), ('approved', 'approved')], default='no', max_length=20)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('garage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage_management.garage')),
            ],
            options={
                'db_table': 'feedback_appointment',
            },
        ),
        migrations.CreateModel(
            name='FeedBackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('is_received', models.CharField(choices=[('no', 'no'), ('yes', 'tes'), ('approved', 'approved')], default='no', max_length=20)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('garage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage_management.garage')),
            ],
            options={
                'db_table': 'feedback_request',
            },
        ),
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
